In [1]:
import numpy as np

In [2]:
l = [1,2,3,4,5]
print(f"l = {l}")

l = [1, 2, 3, 4, 5]


In [3]:
arr = np.array(l)
arr

array([1, 2, 3, 4, 5])

# numpy

In [4]:
arr[[1,2]]

array([2, 3])

In [5]:
cond = arr >= 3  # 筛选大于等于3的数据
cond

array([False, False,  True,  True,  True])

In [6]:
arr[cond]

array([3, 4, 5])

In [7]:
np.ones(shape = 10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [8]:
np.zeros(shape = 5)

array([0., 0., 0., 0., 0.])

In [9]:
np.full(shape = 20, fill_value=3.14)

array([3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14,
       3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14])

In [10]:
np.random.randint(0, 100, size=10)

array([27, 20, 11, 93, 61, 27, 54, 22,  8,  7])

In [11]:
np.random.randn(10)  # 正态分布，平均值是 0，标准差是 1

array([-0.05705345, -1.03980564,  1.89665112, -1.02149296, -0.81742793,
       -0.85418422,  0.3170415 ,  1.29285763, -3.23365755,  0.54612267])

In [12]:
np.linspace(1,99,50) # 等差数列

array([ 1.,  3.,  5.,  7.,  9., 11., 13., 15., 17., 19., 21., 23., 25.,
       27., 29., 31., 33., 35., 37., 39., 41., 43., 45., 47., 49., 51.,
       53., 55., 57., 59., 61., 63., 65., 67., 69., 71., 73., 75., 77.,
       79., 81., 83., 85., 87., 89., 91., 93., 95., 97., 99.])

In [13]:
np.set_printoptions(suppress=True)  # 不显示科学计数法
np.logspace(0,10,base=2,num=11)  # 等比数列

array([   1.,    2.,    4.,    8.,   16.,   32.,   64.,  128.,  256.,
        512., 1024.])

In [14]:
# 二维数组
np.random.randint(0, 10, size=(3,5))

array([[1, 9, 1, 9, 0],
       [5, 3, 0, 3, 4],
       [1, 4, 2, 2, 6]])

In [15]:
# 三维数组
np.random.randint(0, 10, size=(2,3,4))

array([[[3, 4, 3, 3],
        [1, 4, 4, 0],
        [0, 1, 6, 5]],

       [[8, 4, 3, 9],
        [8, 3, 1, 9],
        [1, 8, 5, 7]]])

# 数据查看

In [16]:
arr = np.random.random(size = (3,5))
arr

array([[0.05050598, 0.52598778, 0.31556581, 0.22015179, 0.52301047],
       [0.19719128, 0.41950968, 0.39237632, 0.61780848, 0.23298964],
       [0.61109531, 0.3695958 , 0.00456287, 0.61476167, 0.24307441]])

In [17]:
arr.shape

(3, 5)

In [18]:
arr.dtype

dtype('float64')

In [19]:
arr.size

15

In [20]:
arr.ndim

2

In [21]:
arr.itemsize

8

# 文件保存

In [22]:
arr = np.arange(0,10,3)
arr
np.save("./data1", arr)  # 保存数据

In [23]:
np.load("./data1.npy")  # 读取数据

array([0, 3, 6, 9])

In [24]:
arr2 = np.logspace(0,10,base=2,num=11)
arr2

array([   1.,    2.,    4.,    8.,   16.,   32.,   64.,  128.,  256.,
        512., 1024.])

In [25]:
np.savez("./data2.npz",arr1=arr,arr2=arr2)  # 存多个数据

In [26]:
np.load("./data2.npz")["arr1"]

array([0, 3, 6, 9])

In [27]:
np.load("./data2.npz")["arr2"]

array([   1.,    2.,    4.,    8.,   16.,   32.,   64.,  128.,  256.,
        512., 1024.])

# 数据类型

In [28]:
# 整数
# 浮点数
# 字符串

In [29]:
arr=np.array([2,4,5],dtype=np.int16)
arr

array([2, 4, 5], dtype=int16)

In [30]:
arr=np.array([2,4,5],dtype=np.int32)
arr

array([2, 4, 5], dtype=int32)

In [31]:
arr = np.random.randint(0,100,size=(100,50),dtype=np.int8)
np.save("./data3_int8",arr)

In [32]:
arr = np.random.randint(0,100,size=(100,50),dtype=np.int64)
np.save("./data3_int64",arr)

In [33]:
#int8
arr1 = np.arange(-128,128, dtype=np.int8)
arr1

array([-128, -127, -126, -125, -124, -123, -122, -121, -120, -119, -118,
       -117, -116, -115, -114, -113, -112, -111, -110, -109, -108, -107,
       -106, -105, -104, -103, -102, -101, -100,  -99,  -98,  -97,  -96,
        -95,  -94,  -93,  -92,  -91,  -90,  -89,  -88,  -87,  -86,  -85,
        -84,  -83,  -82,  -81,  -80,  -79,  -78,  -77,  -76,  -75,  -74,
        -73,  -72,  -71,  -70,  -69,  -68,  -67,  -66,  -65,  -64,  -63,
        -62,  -61,  -60,  -59,  -58,  -57,  -56,  -55,  -54,  -53,  -52,
        -51,  -50,  -49,  -48,  -47,  -46,  -45,  -44,  -43,  -42,  -41,
        -40,  -39,  -38,  -37,  -36,  -35,  -34,  -33,  -32,  -31,  -30,
        -29,  -28,  -27,  -26,  -25,  -24,  -23,  -22,  -21,  -20,  -19,
        -18,  -17,  -16,  -15,  -14,  -13,  -12,  -11,  -10,   -9,   -8,
         -7,   -6,   -5,   -4,   -3,   -2,   -1,    0,    1,    2,    3,
          4,    5,    6,    7,    8,    9,   10,   11,   12,   13,   14,
         15,   16,   17,   18,   19,   20,   21,   

In [34]:
#uint8
arr2 = np.arange(0,256, dtype=np.uint8)
arr2

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [35]:
arr1.dtype

dtype('int8')

In [36]:
# 转换数据类型，生成新的数组
arr1.astype(np.float32)

array([-128., -127., -126., -125., -124., -123., -122., -121., -120.,
       -119., -118., -117., -116., -115., -114., -113., -112., -111.,
       -110., -109., -108., -107., -106., -105., -104., -103., -102.,
       -101., -100.,  -99.,  -98.,  -97.,  -96.,  -95.,  -94.,  -93.,
        -92.,  -91.,  -90.,  -89.,  -88.,  -87.,  -86.,  -85.,  -84.,
        -83.,  -82.,  -81.,  -80.,  -79.,  -78.,  -77.,  -76.,  -75.,
        -74.,  -73.,  -72.,  -71.,  -70.,  -69.,  -68.,  -67.,  -66.,
        -65.,  -64.,  -63.,  -62.,  -61.,  -60.,  -59.,  -58.,  -57.,
        -56.,  -55.,  -54.,  -53.,  -52.,  -51.,  -50.,  -49.,  -48.,
        -47.,  -46.,  -45.,  -44.,  -43.,  -42.,  -41.,  -40.,  -39.,
        -38.,  -37.,  -36.,  -35.,  -34.,  -33.,  -32.,  -31.,  -30.,
        -29.,  -28.,  -27.,  -26.,  -25.,  -24.,  -23.,  -22.,  -21.,
        -20.,  -19.,  -18.,  -17.,  -16.,  -15.,  -14.,  -13.,  -12.,
        -11.,  -10.,   -9.,   -8.,   -7.,   -6.,   -5.,   -4.,   -3.,
         -2.,   -1.,

In [37]:
arr1.dtype

dtype('int8')

# 数组运算

In [38]:
nd = np.random.randint(0,10,size=(3,5))
nd

array([[9, 6, 9, 4, 0],
       [8, 5, 1, 2, 5],
       [9, 3, 1, 5, 9]])

In [39]:
nd **2

array([[81, 36, 81, 16,  0],
       [64, 25,  1,  4, 25],
       [81,  9,  1, 25, 81]])

In [40]:
np.power(nd, 2)

array([[81, 36, 81, 16,  0],
       [64, 25,  1,  4, 25],
       [81,  9,  1, 25, 81]])

In [41]:
nd/2

array([[4.5, 3. , 4.5, 2. , 0. ],
       [4. , 2.5, 0.5, 1. , 2.5],
       [4.5, 1.5, 0.5, 2.5, 4.5]])

In [42]:
nd % 2

array([[1, 0, 1, 0, 0],
       [0, 1, 1, 0, 1],
       [1, 1, 1, 1, 1]])

In [43]:
nd // 2

array([[4, 3, 4, 2, 0],
       [4, 2, 0, 1, 2],
       [4, 1, 0, 2, 4]])

In [44]:
nd > 5

array([[ True,  True,  True, False, False],
       [ True, False, False, False, False],
       [ True, False, False, False,  True]])

In [45]:
nd == 6

array([[False,  True, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [46]:
nd

array([[9, 6, 9, 4, 0],
       [8, 5, 1, 2, 5],
       [9, 3, 1, 5, 9]])

In [47]:
# 改变原始数据
nd += 100

In [48]:
nd

array([[109, 106, 109, 104, 100],
       [108, 105, 101, 102, 105],
       [109, 103, 101, 105, 109]])

In [49]:
nd2 = nd.copy()
nd2

array([[109, 106, 109, 104, 100],
       [108, 105, 101, 102, 105],
       [109, 103, 101, 105, 109]])

# 索引和切片

## 一维数组索引和切片

In [50]:
arr = np.random.randint(0,100,size=10)
arr

array([32, 43, 35, 26, 78, 27, 10, 75, 67, 91])

In [51]:
arr[1]

43

In [52]:
arr[[0,3,5]]

array([32, 26, 27])

In [53]:
arr[3:6]

array([26, 78, 27])

In [54]:
arr[3:6:2]

array([26, 27])

In [55]:
arr[::-1]

array([91, 67, 75, 10, 27, 78, 26, 35, 43, 32])

In [56]:
arr[::-3]

array([91, 10, 26, 32])

## 二维数组索引和切片

In [57]:
arr2 = np.random.randint(0,100,size=(3,5))
arr2

array([[25, 58, 97, 15,  4],
       [34, 69, 34, 35, 28],
       [95, 93, 25, 97, 36]])

In [58]:
# 取第0行，第2列的数据
arr2[0,2]

97

In [59]:
# 取1行的第1列和2列 数据
arr2[1,[1,2]]

array([69, 34])

In [60]:
# 获取第1行第3列数据，和第2号第4列数据
arr2[[1,2],[3,4]]

array([35, 36])

In [61]:
# 取第1行第2行以及第3列第4列的数据
arr2[[1,2],3:]

array([[35, 28],
       [97, 36]])

In [62]:
# 取第0行第2行以及第0，2，4列的数据
arr2[[0,2]][:,[0,2,4]]

array([[25, 97,  4],
       [95, 25, 36]])

In [63]:
# 赋值
arr2[2,[2,4]]=1042
arr2

array([[  25,   58,   97,   15,    4],
       [  34,   69,   34,   35,   28],
       [  95,   93, 1042,   97, 1042]])

## 花式索引

In [64]:
arr = np.random.randint(0,100,size=20)
arr

array([57, 27, 54, 33, 68, 53, 48, 99, 19, 90,  2,  8, 69, 34, 81,  3, 84,
        5, 23, 70])

In [65]:
arr[[3,5,7]]

array([33, 53, 99])

In [66]:
# 取出 大于 60 的数据
cond = arr > 60
arr[cond]

array([68, 99, 90, 69, 81, 84, 70])

In [67]:
# 取出 小于30 大于80的数据
cond1 = arr<30
cond2 = arr>80
cond = cond1 | cond2  # 或
arr[cond]

array([27, 99, 19, 90,  2,  8, 81,  3, 84,  5, 23])

In [68]:
# argsort排序
arr2 = np.random.randint(0,100,size=5)
arr2

array([54, 25, 66, 67, 68])

In [69]:
index = np.argsort(arr2)
index  # 原始索引排序后

array([1, 0, 2, 3, 4])

In [70]:
arr2[index]  # 花式索引

array([25, 54, 66, 67, 68])

In [71]:
# 根据第2列的大小顺序，对一个5*5的数组进行排序
arr3 = np.random.randint(0,100,size=(5,5))
arr3

array([[ 3, 56, 47, 71, 34],
       [34, 67, 29, 81, 17],
       [23, 36, 69, 71, 76],
       [81, 86, 10,  8,  7],
       [ 2, 62, 85, 32, 98]])

In [72]:
arr3[np.argsort(arr3[:,2])]  # 花式索引

array([[81, 86, 10,  8,  7],
       [34, 67, 29, 81, 17],
       [ 3, 56, 47, 71, 34],
       [23, 36, 69, 71, 76],
       [ 2, 62, 85, 32, 98]])