## 索引切片

In [1]:
import numpy as np

nd2 = np.random.randint(-5,15,size=(5,6))

nd2

array([[ 3, -4,  7, -2,  2,  4],
       [10, 13,  3, -5, 13, -5],
       [ 2,  3,  5, -3,  1, 11],
       [-2, 10,  9, -2, -3, 12],
       [-1, -5,  8,  8, 10, -2]])

In [2]:
nd2[[1,3]]

array([[10, 13,  3, -5, 13, -5],
       [-2, 10,  9, -2, -3, 12]])

In [3]:
nd2[:,[1,3,5]]

array([[-4, -2,  4],
       [13, -5, -5],
       [ 3, -3, 11],
       [10, -2, 12],
       [-5,  8, -2]])

In [4]:
nd2[[1,3], [1,3,5]]  # 会报错

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (2,) (3,) 

In [ ]:
nd2[[1,4], [3,5]]  # 获取1行3列数据 和 4行5列数据

### 方式1

In [ ]:
nd2[[1,3]][:,[1,3,5]]  # 获取第1、3行 的 第 1、3、5列数据

### 方式2

In [ ]:
np.ix_([1,3],[1,3,5])

In [ ]:
# 获取第1、3行 的 第 1、3、5列数据
index = np.ix_([1,3],[1,3,5])
nd2[index]  # 相当于 nd2[[1,3]][:,[1,3,5]] 

## 形状改变

### reshape

In [ ]:
nd2 = np.random.randint(0,100,size=(3,4))
display(nd2)

# 数据重塑reshape
display(nd2.reshape(4,3))  # 一行一行数

print("2行6列：")
display(nd2.reshape(2,6))
# -1表示最后计算，相当于 x * 6 = 3 * 4  ----> x = 2
display(nd2.reshape(-1,6))

display(nd2.reshape(-1))

In [ ]:
# 下面代码会报错，因为 3*5 不等于 3*4，所以无法转换
nd2.reshape(3,5)

### 叠加

In [ ]:
arr1 = np.random.randint(0,10,size = (2,4))

arr2 = np.random.randint(-5,5,size = (3,4))

display(arr1, arr2)

# 合并，默认进行行合并，行变多
np.concatenate([arr1,arr2])

In [ ]:
arr1 = np.random.randint(0,10,size = (3,5))

arr2 = np.random.randint(-5,5,size = (3,4))

display(arr1, arr2)

# 合并
# axis = 0 默认值，代表行
# axis = 1 代表列
np.concatenate([arr1,arr2],axis = 1)

### 拆分

In [ ]:
nd = np.random.randint(0,100,size=(6,9))
display(nd)

print("行拆分:")
# 给一个数字表示，平均分成多少份
display(np.split(nd, 2))

# 给一个列表，表示，从列表中的索引处进行拆分
display(np.split(nd,[1,4,5],axis=0))

print("列拆分:")
display(np.split(nd,[1,4,5],axis=1))

### 数组转置

In [ ]:
A = np.random.randint(0,10,size=(3,5))

print("原数据")
display(A)

print("reshape:")
display(A.reshape(5,3))

print("转置,行变列，列变行：")
display(A.T)

In [ ]:
np.transpose(A,axes=[1,0])

## 广播

In [ ]:
arr1 = np.random.randint(0,10,size=(5,3))

arr2 = np.arange(1,4)

display(arr1,arr2)

# arr2 只有1行，arr1有5行
# 广播机制：arr2变成了5份，每一份分别和arr1的每一行相加
arr1 + arr2

In [ ]:
arr3 = np.random.randint(0,10,size=(4,5))

# 沿着列的方向，求每行的平均值，结果有4个数
arr4 = arr3.mean(axis = 1) 

display(arr3,arr4)

# 形状改变，4行1列
display(arr4.reshape(4,1))

# arr3有4行，arr4.reshape(4,1)也有4行
# arr3的每一列都减去 arr4.reshape(4,1)
arr3 - arr4.reshape(4,1)

In [ ]:
# 二维数组，在三维数组上广播
arr1 = np.array([0,1,2,3,4,5,6,7]*3).reshape(3,4,2)  # shape(3,4,2)
arr2 = np.array([0,1,2,3,4,5,6,7]).reshape(4,2)  # shape(4,2)

print("三维数组：")
display(arr1)

print("二维数组：")
display(arr2)

print("相加后：")
arr3 = arr1 + arr2  # arr2数组在 arr1数组0轴上，复制3份，分别与arr1数组0轴上的数据相加
display(arr3)

## 通用函数

### 一般函数

In [7]:
# sin(90)
np.sin(np.pi/2)

1.0

In [12]:
print(np.cos(np.pi/2))

# round，保留几位小数
print(np.cos(np.pi/2).round(5))

6.123233995736766e-17
0.0


In [14]:
# 开平方
np.sqrt(1024)

32.0

In [16]:
# 平方
np.square(8)

64

In [46]:
# 3次方
def fun(x):
    return x**3
fun(3)

27

In [47]:
# 开3次方
def fun2(x):
    return x**(1/3)
fun2(27)

3.0

In [21]:
# 3的2次幂
np.power(3,2)

9

In [53]:
# 开3次方
print(np.power(64, 1/3))
print(np.power(64, 1/3).round(1))

3.9999999999999996
4.0


In [22]:
np.log2(16)

4.0

In [28]:
x = np.array([1,5,2,9,3,6,8])
y = np.array([2,4,3,7,1,9,0])
np.maximum(x, y)  # 返回两个数组中,相同索引位置比较大的值，两个数组的形状要一样

array([2, 5, 3, 9, 3, 9, 8])

In [54]:
np.random.seed(1)
arr2 = np.random.randint(0,10,size=(3,2))
display(arr2)
display(arr2[0])
np.inner(arr2[0], arr2)  # 返回一维数组向量内积

array([[5, 8],
       [9, 5],
       [0, 0]])

array([5, 8])

array([89, 85,  0])

In [56]:
a = 3.999
np.ceil(a)  # 向上取整

4.0

In [57]:
np.floor(a)  # 向下取整

3.0

In [59]:
arr = np.random.randint(0,30,size=(20))
arr

array([23, 23,  9, 17, 23,  0, 22, 13,  9,  9,  7, 29, 22, 25,  1,  0, 28,
       17,  8, 24])

In [72]:
# clip裁剪，
# 10：小于10的数据变成10
# 20：大于20的数据变成20
np.clip(arr,10,20)

array([20, 20, 10, 17, 20, 10, 20, 13, 10, 10, 10, 20, 20, 20, 10, 10, 20,
       17, 10, 20])

In [109]:
arr = np.random.randint(0,100,size=(10))
display(arr)
arr.sort()
display(arr)

# 数据总数是基数：直接去中间的数
# 数据总数是偶数：去中间的两个数的和，然后取平均值
print("中位数：", np.median(arr)) 

array([ 2, 85, 93, 36, 46, 80, 27, 72, 28,  2])

array([ 2,  2, 27, 28, 36, 46, 72, 80, 85, 93])

中位数： 41.0


### where函数

In [74]:
import numpy as np
arr1 = np.array([1,3,5,7,9])
arr2 = np.array([2,4,6,8,10])

cond = np.array([True,False,True,True,False])

# 根据条件进行筛选
np.where(cond,arr1,arr2)  # True选择arr1，False选择arr2的值

array([ 1,  4,  5,  7, 10])

In [78]:
arr3 = np.random.randint(0,30,size = 20)
display(arr3)

np.where(arr3 < 15, arr3, -15)  # 小于15还是自己的值，大于15设置成-15

array([10, 14,  0, 24, 23, 23,  1, 17, 13,  3,  0, 24, 29, 13,  6, 20, 21,
        6,  2, 12])

array([ 10,  14,   0, -15, -15, -15,   1, -15,  13,   3,   0, -15, -15,
        13,   6, -15, -15,   6,   2,  12])

In [80]:
# 满分为150分考试成绩的数据，错误数据用 -1024 表示
arr4 = np.random.randint(-10,180,size=50)
arr4

array([104,  87, 171,  74,   0,  86, 173,  51,  46, 139,  86,  15, 132,
       131, 106,  33, 124, 174, 177, 133,  14, 127,  43,  59, 154,  91,
        11,  30,  67, 167, 103,  37, 158,  35,  77, 134, 146,  35, 106,
        56,  36, 118, 147,  53,  65,  25, 171,  23, 120,  73])

In [82]:
np.where((arr4 < 0) | (arr4 > 150), -1024, arr4)

array([  104,    87, -1024,    74,     0,    86, -1024,    51,    46,
         139,    86,    15,   132,   131,   106,    33,   124, -1024,
       -1024,   133,    14,   127,    43,    59, -1024,    91,    11,
          30,    67, -1024,   103,    37, -1024,    35,    77,   134,
         146,    35,   106,    56,    36,   118,   147,    53,    65,
          25, -1024,    23,   120,    73])

### 集合运算函数

In [110]:
A = np.array([2,4,6,8])
B = np.array([3,4,5,6])

print("交集：")
print(np.intersect1d(A,B))

print("并集：")
print(np.union1d(A,B))

print("差集：")
print(np.setdiff1d(A,B)) # A中有，B中没有
print(np.setdiff1d(B,A)) # B中有，A中没有

交集：
[4 6]
并集：
[2 3 4 5 6 8]
差集：
[2 8]
[3 5]


### 矩阵运算

In [113]:
A = np.array([[4,2,3],
              [1,3,1]])  # shape(2,3)
B = np.array([[2,7],
              [-5,-7],
              [9,3]])  # shape(3,2)

print("点乘，矩阵运算：\n", np.dot(A,B)) # 矩阵运算， A的最后一维和B的第一维必须一致

点乘，矩阵运算：
 [[ 25  23]
 [ -4 -11]]


In [115]:
A @ B  # 符号 @ 表示矩阵乘积运算

array([[ 25,  23],
       [ -4, -11]])

In [117]:
A.dot(B)

array([[ 25,  23],
       [ -4, -11]])

In [129]:
# 计算矩阵的逆
from numpy.linalg import inv, det, eig, qr, svd
np.set_printoptions(suppress=True)
A = np.array([
    [1,2,3],
    [2,3,4],
    [4,5,8]
])

print("逆矩阵：")
B = inv(A)  # A的逆矩阵
display(B)

print("单位矩阵：")
A.dot(B)  # 单位矩阵

逆矩阵：


array([[-2. ,  0.5,  0.5],
       [ 0. ,  2. , -1. ],
       [ 1. , -1.5,  0.5]])

单位矩阵：


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [130]:
# 线性代数相关概念，自行复习!!!!!!!!!!!!!!!!!!!!!!
det(A) # 计算矩阵行列式

-2.0000000000000004