In [1]:
import numpy as np

In [2]:
l = [1,2,3,4,5]
print(f"l = {l}")

l = [1, 2, 3, 4, 5]


In [3]:
arr = np.array(l)
arr

array([1, 2, 3, 4, 5])

# numpy

In [4]:
arr[[1,2]]

array([2, 3])

In [5]:
cond = arr >= 3  # 筛选大于等于3的数据
cond

array([False, False,  True,  True,  True])

In [6]:
arr[cond]

array([3, 4, 5])

In [7]:
np.ones(shape = 10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [8]:
np.zeros(shape = 5)

array([0., 0., 0., 0., 0.])

In [9]:
np.full(shape = 20, fill_value=3.14)

array([3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14,
       3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14])

In [10]:
np.random.randint(0, 100, size=10)

array([35, 88, 94,  8, 25, 91, 92, 92, 58, 48])

In [11]:
np.random.randn(10)  # 正态分布，平均值是 0，标准差是 1

array([ 0.9495732 , -1.37805955,  0.22167572,  1.22116488, -0.96333018,
       -1.62945548, -0.89126891, -1.27839099,  0.75038016, -1.041503  ])

In [12]:
np.linspace(1,99,50) # 等差数列（参数1,99是闭区间； 50是分成50份）

array([ 1.,  3.,  5.,  7.,  9., 11., 13., 15., 17., 19., 21., 23., 25.,
       27., 29., 31., 33., 35., 37., 39., 41., 43., 45., 47., 49., 51.,
       53., 55., 57., 59., 61., 63., 65., 67., 69., 71., 73., 75., 77.,
       79., 81., 83., 85., 87., 89., 91., 93., 95., 97., 99.])

In [13]:
np.set_printoptions(suppress=True)  # 不显示科学计数法
np.logspace(0,10,base=2,num=11)  # 等比数列

array([   1.,    2.,    4.,    8.,   16.,   32.,   64.,  128.,  256.,
        512., 1024.])

In [14]:
# 二维数组
np.random.randint(0, 10, size=(3,5))

array([[2, 8, 5, 3, 3],
       [8, 8, 6, 8, 2],
       [7, 2, 5, 3, 5]])

In [15]:
# 三维数组
np.random.randint(0, 10, size=(2,3,4))

array([[[5, 7, 9, 0],
        [8, 0, 1, 1],
        [3, 6, 9, 1]],

       [[2, 6, 5, 6],
        [0, 5, 8, 1],
        [0, 6, 0, 3]]])

# 数据查看

In [16]:
arr = np.random.random(size = (3,5))
arr

array([[0.56994077, 0.90350913, 0.91696149, 0.67360674, 0.57241613],
       [0.57166928, 0.30801911, 0.24293421, 0.69876795, 0.36386736],
       [0.39291748, 0.11480605, 0.09529479, 0.34033519, 0.01573928]])

In [17]:
arr.shape

(3, 5)

In [18]:
arr.dtype

dtype('float64')

In [19]:
arr.size

15

In [20]:
arr.ndim

2

In [21]:
arr.itemsize

8

# 文件保存

In [22]:
arr = np.arange(0,10,3)
arr
np.save("./data1", arr)  # 保存数据

In [23]:
np.load("./data1.npy")  # 读取数据

array([0, 3, 6, 9])

In [24]:
arr2 = np.logspace(0,10,base=2,num=11)
arr2

array([   1.,    2.,    4.,    8.,   16.,   32.,   64.,  128.,  256.,
        512., 1024.])

In [25]:
np.savez("./data2.npz",arr1=arr,arr2=arr2)  # 存多个数据

In [26]:
np.load("./data2.npz")["arr1"]

array([0, 3, 6, 9])

In [27]:
np.load("./data2.npz")["arr2"]

array([   1.,    2.,    4.,    8.,   16.,   32.,   64.,  128.,  256.,
        512., 1024.])

# 数据类型

In [28]:
# 整数
# 浮点数
# 字符串

In [29]:
arr=np.array([2,4,5],dtype=np.int16)
arr

array([2, 4, 5], dtype=int16)

In [30]:
arr=np.array([2,4,5],dtype=np.int32)
arr

array([2, 4, 5])

In [31]:
arr = np.random.randint(0,100,size=(100,50),dtype=np.int8)
np.save("./data3_int8",arr)

In [32]:
arr = np.random.randint(0,100,size=(100,50),dtype=np.int64)
np.save("./data3_int64",arr)

In [33]:
#int8
arr1 = np.arange(-128,128, dtype=np.int8)
arr1

array([-128, -127, -126, -125, -124, -123, -122, -121, -120, -119, -118,
       -117, -116, -115, -114, -113, -112, -111, -110, -109, -108, -107,
       -106, -105, -104, -103, -102, -101, -100,  -99,  -98,  -97,  -96,
        -95,  -94,  -93,  -92,  -91,  -90,  -89,  -88,  -87,  -86,  -85,
        -84,  -83,  -82,  -81,  -80,  -79,  -78,  -77,  -76,  -75,  -74,
        -73,  -72,  -71,  -70,  -69,  -68,  -67,  -66,  -65,  -64,  -63,
        -62,  -61,  -60,  -59,  -58,  -57,  -56,  -55,  -54,  -53,  -52,
        -51,  -50,  -49,  -48,  -47,  -46,  -45,  -44,  -43,  -42,  -41,
        -40,  -39,  -38,  -37,  -36,  -35,  -34,  -33,  -32,  -31,  -30,
        -29,  -28,  -27,  -26,  -25,  -24,  -23,  -22,  -21,  -20,  -19,
        -18,  -17,  -16,  -15,  -14,  -13,  -12,  -11,  -10,   -9,   -8,
         -7,   -6,   -5,   -4,   -3,   -2,   -1,    0,    1,    2,    3,
          4,    5,    6,    7,    8,    9,   10,   11,   12,   13,   14,
         15,   16,   17,   18,   19,   20,   21,   

In [34]:
#uint8
arr2 = np.arange(0,256, dtype=np.uint8)
arr2

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [35]:
arr1.dtype

dtype('int8')

In [36]:
# 转换数据类型，生成新的数组
arr1.astype(np.float32)

array([-128., -127., -126., -125., -124., -123., -122., -121., -120.,
       -119., -118., -117., -116., -115., -114., -113., -112., -111.,
       -110., -109., -108., -107., -106., -105., -104., -103., -102.,
       -101., -100.,  -99.,  -98.,  -97.,  -96.,  -95.,  -94.,  -93.,
        -92.,  -91.,  -90.,  -89.,  -88.,  -87.,  -86.,  -85.,  -84.,
        -83.,  -82.,  -81.,  -80.,  -79.,  -78.,  -77.,  -76.,  -75.,
        -74.,  -73.,  -72.,  -71.,  -70.,  -69.,  -68.,  -67.,  -66.,
        -65.,  -64.,  -63.,  -62.,  -61.,  -60.,  -59.,  -58.,  -57.,
        -56.,  -55.,  -54.,  -53.,  -52.,  -51.,  -50.,  -49.,  -48.,
        -47.,  -46.,  -45.,  -44.,  -43.,  -42.,  -41.,  -40.,  -39.,
        -38.,  -37.,  -36.,  -35.,  -34.,  -33.,  -32.,  -31.,  -30.,
        -29.,  -28.,  -27.,  -26.,  -25.,  -24.,  -23.,  -22.,  -21.,
        -20.,  -19.,  -18.,  -17.,  -16.,  -15.,  -14.,  -13.,  -12.,
        -11.,  -10.,   -9.,   -8.,   -7.,   -6.,   -5.,   -4.,   -3.,
         -2.,   -1.,

In [37]:
arr1.dtype

dtype('int8')

# 数组运算

In [38]:
nd = np.random.randint(0,10,size=(3,5))
nd

array([[6, 3, 9, 3, 3],
       [6, 6, 0, 4, 8],
       [3, 6, 5, 1, 2]])

In [39]:
nd **2

array([[36,  9, 81,  9,  9],
       [36, 36,  0, 16, 64],
       [ 9, 36, 25,  1,  4]])

In [40]:
np.power(nd, 2)

array([[36,  9, 81,  9,  9],
       [36, 36,  0, 16, 64],
       [ 9, 36, 25,  1,  4]], dtype=int32)

In [41]:
nd/2

array([[3. , 1.5, 4.5, 1.5, 1.5],
       [3. , 3. , 0. , 2. , 4. ],
       [1.5, 3. , 2.5, 0.5, 1. ]])

In [42]:
nd % 2

array([[0, 1, 1, 1, 1],
       [0, 0, 0, 0, 0],
       [1, 0, 1, 1, 0]], dtype=int32)

In [43]:
nd // 2

array([[3, 1, 4, 1, 1],
       [3, 3, 0, 2, 4],
       [1, 3, 2, 0, 1]], dtype=int32)

In [44]:
nd > 5

array([[ True, False,  True, False, False],
       [ True,  True, False, False,  True],
       [False,  True, False, False, False]])

In [45]:
nd == 6

array([[ True, False, False, False, False],
       [ True,  True, False, False, False],
       [False,  True, False, False, False]])

In [46]:
nd

array([[6, 3, 9, 3, 3],
       [6, 6, 0, 4, 8],
       [3, 6, 5, 1, 2]])

In [47]:
# 改变原始数据
nd += 100

In [48]:
nd

array([[106, 103, 109, 103, 103],
       [106, 106, 100, 104, 108],
       [103, 106, 105, 101, 102]])

In [49]:
nd2 = nd.copy()
nd2

array([[106, 103, 109, 103, 103],
       [106, 106, 100, 104, 108],
       [103, 106, 105, 101, 102]])

# 索引和切片

## 一维数组索引和切片

In [50]:
arr = np.random.randint(0,100,size=10)
arr

array([51,  5, 49, 85, 73, 49, 11,  2, 92, 45])

In [51]:
arr[1]

5

In [52]:
arr[[0,3,5]]

array([51, 85, 49])

In [53]:
arr[3:6]

array([85, 73, 49])

In [54]:
arr[3:6:2]

array([85, 49])

In [55]:
arr[::-1]

array([45, 92,  2, 11, 49, 73, 85, 49,  5, 51])

In [56]:
arr[::-3]

array([45, 11, 85, 51])

## 二维数组索引和切片

In [57]:
arr2 = np.random.randint(0,100,size=(3,5))
arr2

array([[69, 29, 78, 58, 28],
       [98, 79, 65, 15, 12],
       [ 7, 22, 28, 77, 63]])

In [58]:
# 取第0行，第2列的数据
arr2[0,2]

78

In [59]:
# 取1行的第1列和2列 数据
arr2[1,[1,2]]

array([79, 65])

In [60]:
# 获取第1行第3列数据，和第2号第4列数据
arr2[[1,2],[3,4]]

array([15, 63])

In [61]:
# 取第1行第2行以及第3列第4列的数据
arr2[[1,2],3:]

array([[15, 12],
       [77, 63]])

In [62]:
# 取第0行第2行以及第0，2，4列的数据
arr2[[0,2]][:,[0,2,4]]

array([[69, 78, 28],
       [ 7, 28, 63]])

In [63]:
# 赋值
arr2[2,[2,4]]=1042
arr2

array([[  69,   29,   78,   58,   28],
       [  98,   79,   65,   15,   12],
       [   7,   22, 1042,   77, 1042]])

## 花式索引

In [64]:
arr = np.random.randint(0,100,size=20)
arr

array([95, 53,  4, 58,  0, 45, 79,  6, 95, 26, 26, 33, 34, 94, 19, 44, 81,
       82, 94,  1])

In [65]:
arr[[3,5,7]]

array([58, 45,  6])

In [66]:
# 取出 大于 60 的数据
cond = arr > 60
arr[cond]

array([95, 79, 95, 94, 81, 82, 94])

In [67]:
# 取出 小于30 大于80的数据
cond1 = arr<30
cond2 = arr>80
cond = cond1 | cond2  # 或
arr[cond]

array([95,  4,  0,  6, 95, 26, 26, 94, 19, 81, 82, 94,  1])

In [68]:
# argsort排序
arr2 = np.random.randint(0,100,size=5)
arr2

array([89, 91, 64, 10, 96])

In [69]:
index = np.argsort(arr2)
index  # 原始索引排序后

array([3, 2, 0, 1, 4], dtype=int64)

In [70]:
arr2[index]  # 花式索引

array([10, 64, 89, 91, 96])

In [71]:
# 根据第2列的大小顺序，对一个5*5的数组进行排序
arr3 = np.random.randint(0,100,size=(5,5))
arr3

array([[92,  0, 74, 63, 76],
       [82, 15, 48, 38, 28],
       [39, 57, 42, 58, 14],
       [75, 84, 71, 45, 34],
       [66,  6, 48, 67, 71]])

In [73]:
arr3[np.argsort(arr3[:,2])]  # 花式索引

array([[39, 57, 42, 58, 14],
       [82, 15, 48, 38, 28],
       [66,  6, 48, 67, 71],
       [75, 84, 71, 45, 34],
       [92,  0, 74, 63, 76]])

# 作业

## 作业4

In [76]:
arr = np.random.randint(0,100,size=30)
display(arr)
# 获取最大值，最小值
print(f"最大值：{arr.max()}")
print(f"最小值：{arr.min()}")

array([15, 42, 24, 31, 19, 23, 82, 47, 36, 63, 32,  2, 11, 89, 56, 90, 24,
       12, 15, 35,  0, 94, 74, 17,  0, 36, 21, 45, 48, 26])

最大值：94
最小值：0


## 作业5

In [84]:
# 创建一个10*10的ndarray对象，且矩阵边界全为1，里面全为0
arr = np.zeros(shape=(10,10),dtype=np.int8)
arr[[0,-1]] = 1  # 通过索引给行赋值
arr[:,[0,-1]] = 1  # 通过索引给列赋值
arr

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=int8)

## 作业6

In [90]:
# 创建一个每一行都是 0到4的 5*5的矩阵
arr = np.full(shape=(5,5), fill_value=3.14)
arr2 = np.arange(0,5)
arr[:] = arr2  # 将arr的每一行都替换为arr2
arr

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

## 作业7

In [96]:
np.set_printoptions(suppress=True)  # 不显示科学计数法
np.logspace(0,10,base=2,num=11)  # 等比数列： 2^0 到 2^10

array([   1.,    2.,    4.,    8.,   16.,   32.,   64.,  128.,  256.,
        512., 1024.])

## 作业8

In [101]:
# 创建一个长度为10的正态分布，并排序
arr = np.random.randn(10)
print("未排序:", arr)
arr2 = np.sort(arr)
print("已排序:", arr2)

未排序: [ 0.44802958 -0.75047933  0.31144623  0.12758561  0.98260547 -1.41950858
 -0.86122    -0.1936521  -0.02873362  0.2745285 ]
已排序: [-1.41950858 -0.86122    -0.75047933 -0.1936521  -0.02873362  0.12758561
  0.2745285   0.31144623  0.44802958  0.98260547]


## 作业9

In [115]:
# 创建一个长度为10的随机数组，并将最大值替换为 -100
np.set_printoptions(suppress=True)
arr = np.random.random(10)
print("原数据:\n", arr)

# 找到最大值
v = arr.max()

# 进行条件判断
cond = arr==v
print("最大值条件:\n", cond)

# 根据条件赋值
arr[cond] = -100
print("修改之后数据:\n", arr)

原数据:
 [0.66335809 0.77104895 0.55910169 0.31914529 0.59785255 0.37520336
 0.45693788 0.61612596 0.17071445 0.8835054 ]
最大值条件:
 [False False False False False False False False False  True]
修改之后数据:
 [   0.66335809    0.77104895    0.55910169    0.31914529    0.59785255
    0.37520336    0.45693788    0.61612596    0.17071445 -100.        ]


## 作业10

In [144]:
# 根据第3列大小顺序对一个5*5矩阵进行排序
np.random.seed(10)
arr = np.random.randint(0,100,(5,5))
print("原数据：\n", arr, "\n")

print("第三列数据：", arr[:,2], "\n")

indices = np.argsort(arr[:,2])
print("根据第三列数据升序排列后，原数据索引的位置：", indices, "\n")

arr2 = arr[indices]  # 花式索引
print("根据第3列大小顺序排序后数据：\n", arr2, "\n")


原数据：
 [[ 9 15 64 28 89]
 [93 29  8 73  0]
 [40 36 16 11 54]
 [88 62 33 72 78]
 [49 51 54 77 69]] 

第三列数据： [64  8 16 33 54] 

根据第三列数据升序排列后，原数据索引的位置： [1 2 3 4 0] 

根据第3列大小顺序排序后数据：
 [[93 29  8 73  0]
 [40 36 16 11 54]
 [88 62 33 72 78]
 [49 51 54 77 69]
 [ 9 15 64 28 89]] 

