## 索引切片

In [3]:
import numpy as np

nd2 = np.random.randint(-5,15,size=(5,6))

nd2

array([[ 6, -2,  4,  9,  2,  8],
       [ 3, -3, 13, -3,  8, 12],
       [ 5, 12, 11,  9, 13, -5],
       [10, -5,  8, 13, 14,  7],
       [14, -4,  6, 12, -3,  4]])

In [7]:
nd2[[1,3]]

array([[ 3, -3, 13, -3,  8, 12],
       [10, -5,  8, 13, 14,  7]])

In [9]:
nd2[:,[1,3,5]]

array([[-2,  9,  8],
       [-3, -3, 12],
       [12,  9, -5],
       [-5, 13,  7],
       [-4, 12,  4]])

In [11]:
nd2[[1,3], [1,3,5]]

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (2,) (3,) 

In [14]:
nd2[[1,4], [3,5]]  # 获取1行3列数据 和 4行5列数据

array([-3,  4])

### 方式1

In [15]:
nd2[[1,3]][:,[1,3,5]]  # 获取第1、3行 的 第 1、3、5列数据

array([[-3, -3, 12],
       [-5, 13,  7]])

### 方式2

In [17]:
np.ix_([1,3],[1,3,5])

(array([[1],
        [3]]),
 array([[1, 3, 5]]))

In [20]:
# 获取第1、3行 的 第 1、3、5列数据
index = np.ix_([1,3],[1,3,5])
nd2[index]  # 相当于 nd2[[1,3]][:,[1,3,5]] 

array([[-3, -3, 12],
       [-5, 13,  7]])

## 形状改变