## 索引切片

In [3]:
import numpy as np

nd2 = np.random.randint(-5,15,size=(5,6))

nd2

array([[ 6, -2,  4,  9,  2,  8],
       [ 3, -3, 13, -3,  8, 12],
       [ 5, 12, 11,  9, 13, -5],
       [10, -5,  8, 13, 14,  7],
       [14, -4,  6, 12, -3,  4]])

In [7]:
nd2[[1,3]]

array([[ 3, -3, 13, -3,  8, 12],
       [10, -5,  8, 13, 14,  7]])

In [9]:
nd2[:,[1,3,5]]

array([[-2,  9,  8],
       [-3, -3, 12],
       [12,  9, -5],
       [-5, 13,  7],
       [-4, 12,  4]])

In [11]:
nd2[[1,3], [1,3,5]]  # 会报错

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (2,) (3,) 

In [14]:
nd2[[1,4], [3,5]]  # 获取1行3列数据 和 4行5列数据

array([-3,  4])

### 方式1

In [15]:
nd2[[1,3]][:,[1,3,5]]  # 获取第1、3行 的 第 1、3、5列数据

array([[-3, -3, 12],
       [-5, 13,  7]])

### 方式2

In [17]:
np.ix_([1,3],[1,3,5])

(array([[1],
        [3]]),
 array([[1, 3, 5]]))

In [20]:
# 获取第1、3行 的 第 1、3、5列数据
index = np.ix_([1,3],[1,3,5])
nd2[index]  # 相当于 nd2[[1,3]][:,[1,3,5]] 

array([[-3, -3, 12],
       [-5, 13,  7]])

## 形状改变

### reshape

In [30]:
nd2 = np.random.randint(0,100,size=(3,4))
display(nd2)

# 数据重塑reshape
display(nd2.reshape(4,3))  # 一行一行数

print("2行6列：")
display(nd2.reshape(2,6))
# -1表示最后计算，相当于 x * 6 = 3 * 4  ----> x = 2
display(nd2.reshape(-1,6))

display(nd2.reshape(-1))

array([[27, 84, 36, 19],
       [76, 53, 20,  5],
       [94, 79, 81, 47]])

array([[27, 84, 36],
       [19, 76, 53],
       [20,  5, 94],
       [79, 81, 47]])

2行6列：


array([[27, 84, 36, 19, 76, 53],
       [20,  5, 94, 79, 81, 47]])

array([[27, 84, 36, 19, 76, 53],
       [20,  5, 94, 79, 81, 47]])

array([27, 84, 36, 19, 76, 53, 20,  5, 94, 79, 81, 47])

In [32]:
# 下面代码会报错，因为 3*5 不等于 3*4，所以无法转换
nd2.reshape(3,5)

ValueError: cannot reshape array of size 12 into shape (3,5)

### 叠加

In [36]:
arr1 = np.random.randint(0,10,size = (2,4))

arr2 = np.random.randint(-5,5,size = (3,4))

display(arr1, arr2)

# 合并，默认进行行合并，行变多
np.concatenate([arr1,arr2])

array([[8, 3, 6, 6],
       [1, 4, 5, 3]])

array([[ 4,  0, -2, -2],
       [ 2,  2,  0, -4],
       [ 4, -1, -2, -1]])

array([[ 8,  3,  6,  6],
       [ 1,  4,  5,  3],
       [ 4,  0, -2, -2],
       [ 2,  2,  0, -4],
       [ 4, -1, -2, -1]])

In [44]:
arr1 = np.random.randint(0,10,size = (3,5))

arr2 = np.random.randint(-5,5,size = (3,4))

display(arr1, arr2)

# 合并
# axis = 0 默认值，代表行
# axis = 1 代表列
np.concatenate([arr1,arr2],axis = 1)

array([[1, 6, 6, 8, 6],
       [2, 7, 5, 6, 7],
       [3, 9, 3, 2, 7]])

array([[-2, -5,  4,  0],
       [-2,  1,  3, -4],
       [ 1,  0,  4, -5]])

array([[ 1,  6,  6,  8,  6, -2, -5,  4,  0],
       [ 2,  7,  5,  6,  7, -2,  1,  3, -4],
       [ 3,  9,  3,  2,  7,  1,  0,  4, -5]])

### 拆分

In [55]:
nd = np.random.randint(0,100,size=(6,9))
display(nd)

print("行拆分:")
# 给一个数字表示，平均分成多少份
display(np.split(nd, 2))

# 给一个列表，表示，从列表中的索引处进行拆分
display(np.split(nd,[1,4,5],axis=0))

print("列拆分:")
display(np.split(nd,[1,4,5],axis=1))

array([[ 9, 12, 35, 71, 42, 86, 61, 21, 29],
       [64, 33, 91, 41, 62, 11, 40, 87, 40],
       [48,  9, 97, 84, 29, 55, 28, 70, 19],
       [79, 92, 11, 62, 51, 39, 96, 26, 65],
       [58, 57, 36, 33, 56, 43, 86, 71, 72],
       [64, 82,  6,  3,  0, 12, 23, 52, 41]])

行拆分:


[array([[ 9, 12, 35, 71, 42, 86, 61, 21, 29],
        [64, 33, 91, 41, 62, 11, 40, 87, 40],
        [48,  9, 97, 84, 29, 55, 28, 70, 19]]),
 array([[79, 92, 11, 62, 51, 39, 96, 26, 65],
        [58, 57, 36, 33, 56, 43, 86, 71, 72],
        [64, 82,  6,  3,  0, 12, 23, 52, 41]])]

[array([[ 9, 12, 35, 71, 42, 86, 61, 21, 29]]),
 array([[64, 33, 91, 41, 62, 11, 40, 87, 40],
        [48,  9, 97, 84, 29, 55, 28, 70, 19],
        [79, 92, 11, 62, 51, 39, 96, 26, 65]]),
 array([[58, 57, 36, 33, 56, 43, 86, 71, 72]]),
 array([[64, 82,  6,  3,  0, 12, 23, 52, 41]])]

列拆分:


[array([[ 9],
        [64],
        [48],
        [79],
        [58],
        [64]]),
 array([[12, 35, 71],
        [33, 91, 41],
        [ 9, 97, 84],
        [92, 11, 62],
        [57, 36, 33],
        [82,  6,  3]]),
 array([[42],
        [62],
        [29],
        [51],
        [56],
        [ 0]]),
 array([[86, 61, 21, 29],
        [11, 40, 87, 40],
        [55, 28, 70, 19],
        [39, 96, 26, 65],
        [43, 86, 71, 72],
        [12, 23, 52, 41]])]

### 数组转置

In [62]:
A = np.random.randint(0,10,size=(3,5))

print("原数据")
display(A)

print("reshape:")
display(A.reshape(5,3))

print("转置,行变列，列变行：")
display(A.T)

原数据


array([[0, 4, 5, 5, 0],
       [9, 9, 7, 3, 2],
       [4, 4, 2, 5, 3]])

reshape:


array([[0, 4, 5],
       [5, 0, 9],
       [9, 7, 3],
       [2, 4, 4],
       [2, 5, 3]])

转置,行变列，列变行：


array([[0, 9, 4],
       [4, 9, 4],
       [5, 7, 2],
       [5, 3, 5],
       [0, 2, 3]])

In [68]:
np.transpose(A,axes=[1,0])

array([[0, 9, 4],
       [4, 9, 4],
       [5, 7, 2],
       [5, 3, 5],
       [0, 2, 3]])