## 作业1
给定一个4维矩阵，如何得到最后两维的和？（提示，指定axis进行计算）

In [1]:
import numpy as np
arr = np.random.randint(0,10,size=(2,3,4,5))

display(arr)

# 最后两维的和
display(arr.sum(axis = (-1,-2)))

display(arr[0][0].sum())

array([[[[8, 9, 9, 8, 1],
         [7, 0, 5, 2, 3],
         [2, 2, 7, 6, 5],
         [9, 5, 3, 8, 1]],

        [[4, 5, 6, 3, 8],
         [4, 3, 9, 3, 4],
         [3, 5, 7, 2, 3],
         [4, 4, 3, 7, 8]],

        [[3, 8, 6, 2, 4],
         [9, 4, 8, 3, 7],
         [5, 2, 4, 8, 0],
         [9, 9, 9, 2, 0]]],


       [[[6, 3, 5, 6, 5],
         [9, 2, 0, 3, 1],
         [2, 0, 6, 8, 6],
         [1, 2, 8, 8, 9]],

        [[5, 8, 0, 0, 6],
         [2, 1, 1, 5, 8],
         [4, 0, 3, 8, 5],
         [6, 1, 9, 5, 5]],

        [[3, 3, 5, 0, 1],
         [0, 5, 5, 6, 0],
         [3, 2, 6, 5, 2],
         [7, 8, 2, 8, 3]]]])

array([[100,  95, 102],
       [ 90,  82,  74]])

100

## 作业2
给定数组[1,2,3,4,5]，如何得到在这个数组的每个元素之间插入3个0后的新数据

In [2]:
import numpy as np
arr1 = np.arange(1,6)
print(arr1)

arr2 = np.zeros(shape = 17, dtype=np.int16)
print(arr2)

# 对特定位置的数据进行赋值操作
arr2[::4] = arr1
print("赋值后的数据：\n", arr2)

[1 2 3 4 5]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
赋值后的数据：
 [1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5]


## 作业3
给定一个二维矩阵（5行4列），如何交换其中两行的元素（提示：任意调整，花式索引）

In [3]:
import numpy as np
arr = np.random.randint(0,100,size=(5,4))

print("调整前：\n", arr)

arr = arr[[2,1,0,3,4]] # 调换第1行和第3行
print("调整后：\n", arr)

调整前：
 [[93 38 32 97]
 [63  1 26 54]
 [47  1 97 73]
 [46 33 80 71]
 [99 17 19 88]]
调整后：
 [[47  1 97 73]
 [63  1 26 54]
 [93 38 32 97]
 [46 33 80 71]
 [99 17 19 88]]


## 作业4
创建一个100000长度的随机数组，使用两种方法对其球三次方（1、for循环，2、NumPy自带方法），比较所用时间（指令%%time，可以计算运行时间）

In [4]:
%%time
 # %%time计算其下面代码的运行时间
import numpy as np
arr = np.random.randint(0,10,size=100000)
print("原数据；", arr[:10])
arr3 = np.power(arr,3)
print("NumPy默认方法球三次幂：", arr3[:10])

原数据； [4 6 5 4 1 1 9 0 7 9]
NumPy默认方法球三次幂： [ 64 216 125  64   1   1 729   0 343 729]
CPU times: total: 0 ns
Wall time: 2.01 ms


In [5]:
%%time
import numpy as np
arr = np.random.randint(0,10,size=100000)
print("原数据；", arr[:10])
result = []
for i in arr:
    result.append(i**3)
print("for循环求三次幂结果：", result[:10])

原数据； [7 7 5 5 9 0 0 9 8 1]
for循环求三次幂结果： [343, 343, 125, 125, 729, 0, 0, 729, 512, 1]
CPU times: total: 0 ns
Wall time: 10 ms


## 作业5
创建一个5行3列随机矩阵和一个3行2列随机矩阵，求举证乘积

In [6]:
import numpy as np
A = np.random.randint(0,10,size=(5,3))
B = np.random.randint(0,10,size=(3,2))
display(A,B)


print("方法一：\n", np.dot(A,B))
print("方法二：\n", A.dot(B))
print("方法三：\n", A @ B)

array([[7, 8, 8],
       [6, 7, 3],
       [5, 2, 8],
       [9, 4, 3],
       [0, 6, 6]])

array([[8, 1],
       [0, 9],
       [9, 0]])

方法一：
 [[128  79]
 [ 75  69]
 [112  23]
 [ 99  45]
 [ 54  54]]
方法二：
 [[128  79]
 [ 75  69]
 [112  23]
 [ 99  45]
 [ 54  54]]
方法三：
 [[128  79]
 [ 75  69]
 [112  23]
 [ 99  45]
 [ 54  54]]


## 作业6
矩阵的每一行的元素都减去该行的平均值（注意，平均值计算式制定axis，以及减法操作时形状改变）

In [7]:
X = np.random.randint(0,10,size=(3,5))
display(X)

print("计算每一行平均值：")
display(X.mean(axis = 1)) # 1行3列
display(X.mean(axis = 1).reshape(-1,1))  # 变成3行1列
X - X.mean(axis = 1).reshape(-1,1) 

array([[7, 1, 2, 6, 9],
       [5, 4, 1, 0, 1],
       [2, 7, 0, 4, 5]])

计算每一行平均值：


array([5. , 2.2, 3.6])

array([[5. ],
       [2.2],
       [3.6]])

array([[ 2. , -4. , -3. ,  1. ,  4. ],
       [ 2.8,  1.8, -1.2, -2.2, -1.2],
       [-1.6,  3.4, -3.6,  0.4,  1.4]])

## 作业7
打印出以下二维数组（要求使用np.zeros创建8*8的矩阵）
```
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [8]:
import numpy as np
arr = np.zeros(shape = (8,8),dtype=np.int16)

print('原数据：')
display(arr)

# 将奇数行的偶数列，进行修改
arr[::2,1::2] = 1

# 将偶数行的奇数列，进行修改
arr[1::2,::2] = 1
print('修改后的数据是：')
arr

原数据：


array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]], dtype=int16)

修改后的数据是：


array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]], dtype=int16)

## 作业8
正则化一个5行5列的随机矩阵（数据统一变成0~1之间的数字，相当于进行缩小）
正则的概念：矩阵A中的每一列减去这一列最小值，除以每一列的最大值减去每一列的最小值（提示：轴axis给合适的参数！！！）
			
$$
 \rm{ A = \frac{A - A.min}{A.max - A.min}}
$$

In [10]:
import numpy as np
A = np.random.randint(1,10,size = (5,5))

print('原数据为：')
display(A)

# 根据公式进行计算，注意axis，要正确指定
B = (A - A.min(axis = 0))/(A.max(axis = 0) - A.min(axis = 0))
print('正则化后：')
B

原数据为：


array([[7, 9, 2, 6, 4],
       [3, 8, 7, 8, 2],
       [4, 4, 9, 7, 8],
       [3, 9, 6, 6, 1],
       [3, 2, 1, 9, 4]])

正则化后：


array([[1.        , 1.        , 0.125     , 0.        , 0.42857143],
       [0.        , 0.85714286, 0.75      , 0.66666667, 0.14285714],
       [0.25      , 0.28571429, 1.        , 0.33333333, 1.        ],
       [0.        , 1.        , 0.625     , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 1.        , 0.42857143]])

## 作业9
如何根据两个或多个条件过滤numpy数组。加载鸢尾花数据，根据第一列小于5.0并且第三列大于1.5作为条件，进行数据筛选。（提示，需要使用逻辑与运算：&）

In [17]:
import numpy as np

# 加载了文本文件，储存数据都是结构化的数据
# 鸢尾花数据：花萼长度、花萼宽度、花瓣长度、花瓣宽度
iris = np.loadtxt('./iris.csv',delimiter = ',')
print(iris.shape)

cond1 = iris[:,0] < 5  # 第一列小于5.0
cond2 = iris[:,2] > 1.5  # 第三列大于1.5
cond = cond1 & cond2  # 合并条件

# 获取数据
iris[cond]

(150, 4)


array([[4.8, 3.4, 1.6, 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [4.9, 2.4, 3.3, 1. ],
       [4.9, 2.5, 4.5, 1.7]])

## 作业10
计算鸢尾花数据每一行的softmax得分（exp表示自然底数e的幂运算）
![](./softmax.png)

In [19]:
np.exp(2)  # exp：以e为底数的幂运算

7.38905609893065

In [21]:
np.e**2

7.3890560989306495

In [22]:
arr = np.array([2,1,0.1])
arr

array([2. , 1. , 0.1])

In [24]:
exp = np.exp(arr)
exp

array([7.3890561 , 2.71828183, 1.10517092])

In [27]:
print((exp/exp.sum()))
print((exp/exp.sum()).round(1))

[0.65900114 0.24243297 0.09856589]
[0.7 0.2 0.1]


In [44]:
import numpy as np

iris = np.loadtxt('./iris.csv',delimiter = ',')

print('未计算之前：\n', iris[:5])

def softmax(x):
    exp = np.exp(x)
    # 每一行求和，并且进行形状改变（变成二维，可以进行广播）
    result = exp/exp.sum(axis = 1).reshape(-1,1)
    return result.round(3) # 保留3位小数

result = softmax(iris)
print('softmax得分：\n',result[:5])

未计算之前：
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
softmax得分：
 [[0.81  0.164 0.02  0.006]
 [0.841 0.126 0.025 0.008]
 [0.789 0.176 0.026 0.009]
 [0.781 0.174 0.035 0.01 ]
 [0.78  0.192 0.021 0.006]]


In [45]:
# 对鸢尾花每一行的 softmax 结果，每一行的和都是 1
# 有的行的求和结果有小数位，是因上面的结果保留了3位小时，计算机浮点数有误差
result.sum(axis = 1)

array([1.   , 1.   , 1.   , 1.   , 0.999, 1.   , 1.   , 1.   , 1.   ,
       1.001, 1.001, 1.   , 1.001, 1.   , 1.   , 1.001, 0.999, 1.   ,
       1.001, 0.999, 1.   , 0.999, 0.999, 1.   , 1.   , 1.   , 1.   ,
       1.   , 1.   , 1.   , 1.   , 0.999, 0.999, 1.001, 1.001, 1.   ,
       1.   , 1.   , 0.999, 0.999, 1.001, 1.   , 1.   , 1.   , 1.   ,
       1.001, 1.   , 0.999, 1.   , 1.   , 1.   , 1.   , 0.999, 1.   ,
       1.001, 1.   , 0.999, 1.001, 0.999, 1.   , 1.   , 1.   , 1.   ,
       0.999, 0.999, 1.   , 1.   , 1.   , 1.   , 0.999, 1.   , 1.   ,
       1.   , 1.001, 1.   , 1.   , 1.   , 1.   , 1.   , 1.   , 0.999,
       1.   , 0.999, 0.999, 1.   , 1.   , 1.   , 1.   , 1.   , 1.   ,
       1.001, 1.   , 1.   , 1.   , 0.999, 1.   , 0.999, 1.   , 1.   ,
       1.   , 1.   , 1.   , 1.   , 1.   , 1.   , 1.   , 1.   , 1.   ,
       1.   , 1.   , 0.999, 1.   , 1.   , 1.   , 1.   , 0.999, 0.999,
       1.   , 1.   , 1.001, 1.001, 0.999, 0.999, 1.   , 1.001, 0.999,
       1.001, 0.999,